version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: leonardo-jacomussi
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
