
version: '3.5'
services:

  db:
    container_name: db
    image: mongo
    restart: 'always'
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    healthcheck:
      test: "mongosh --eval 'db.runCommand({ping: 1}) ? 0 : 1'"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s

  backend:
    container_name: backend
    build: backend
    ports:
      - 3001:3001
    environment:
      - BE_PORT=3001
      - DB_USER=user
      - DB_PASS=12345678
      - DB_NAME=data_base_1
      - DB_URI=mongodb://db:27017

    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:3001
