[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::DeprecationWarning:passlib
    ignore::pydantic.warnings.PydanticDeprecatedSince20