version: '3.7'

services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=challenge
    volumes:
      - challenge_pg_data:/bitnami/postgresql

volumes:
  challenge_pg_data:
