import React from 'react';
import Head from 'next/head'
import type {} from '@mui/x-date-pickers/themeAugmentation';
import DataCreate from '@/interfaces/dataCreate';
import FormDyna from '@/components/form';
import apiFake from './api/fakeApi';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';
import LogOut from '@/components/Logout';
import { createNewProduct } from './api/CRUD/create';
import { formatDataFunction } from '@/middlewares/formtData';


export default function Home() {
  const {data: session} = useSession();
  const router = useRouter()

  const create = async (data: DataCreate) => {
    createNewProduct(formatDataFunction(data));
    router.push('/Dashboard')
  }

if (session) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <FormDyna 
        title="CADASTRAR PRODUTOS"
        btnName="cadastrar"
        func={create} values={undefined}        />
    </>
  )
} else {
  return <LogOut />
}
}
