import React, { useEffect, useState } from "react"
import Head from 'next/head'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
import styles from '../styles/dashboard.module.css'
import Box from '@mui/material/Box';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import type {} from '@mui/x-data-grid/themeAugmentation';
import Divider from '@mui/material/Divider';
import { useRouter } from 'next/router';
import apiFake from "./api/fakeApi";
import { useDispatch } from "react-redux";
import { editProduct } from "@/slices/editSlic";
import DataCreate from "@/interfaces/dataCreate";
import { useSession } from "next-auth/react";
import TopBar from "@/components/TopBar";
import LogOut from "@/components/Logout";
import { deleteDataApi } from "./api/CRUD/delete";

const columns: GridColDef[] = [
  {
    field: 'name',
    headerName: 'Nome',
    width: 150,
    editable: true,
  },
  {
    field: 'fabricationDate',
    headerName: 'Data de Fabricação',
    width: 150,
    editable: true,
  },
  
  {
    field: 'perecive',
    headerName: 'Perecivel',
    type: 'boolean',
    width: 110,
    editable: true,
  },
  {
    field: 'validate',
    headerName: 'Data de Validade',
    width: 150,
    editable: true,
  },
  {
    field: 'price',
    headerName: 'Preço',
    width: 160,
  },
  { field: 'id', headerName: 'ID', width: 90 },
];

export default function Home() {
  const router = useRouter()
  const {data: session} = useSession();
  

    const [disabledButton, setDisabled] = useState(true)
    const [rows, setRows] = useState<any>([])
    const [id, setId] = useState('')
    const dispatch = useDispatch()

    const selectedRow = (data:DataCreate) => {
      dispatch(editProduct(data))
      setDisabled(false)
      if(data.id){
        setId(data.id);
      }
    }

    const fetchData = async() => {
      const data = await apiFake.get('products');
      setRows(data.data);
    } 

    const deleteRow = async() => {
      deleteDataApi(id);
      fetchData()
    }
    useEffect(()=> {
      fetchData()
    }, [])
    if(session) {
      return (
        <>
          <Head>
            <title>DashBoard</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <TopBar />
          <div className={styles.dashboard}>
            <Box sx={{
                width: 900,
                height: 550,
                backgroundColor: "#f6f5f4",
                borderRadius: 2, 
                display: 'flex',
                flexDirection:"column",
                alignItems: 'center',
                justifyContent: 'center',
          }}>
              <Stack spacing={2} direction="row" divider={<Divider orientation="vertical" flexItem />}>
                <Button variant="outlined" onClick={() => router.push('/Create')}>Criação</Button>
                <Button variant="outlined" onClick={() => router.push('/Edit')}disabled={disabledButton}>Edição</Button>
                <Button variant="outlined" type="submit" onClick={deleteRow}disabled={disabledButton}>Deletar</Button>
              </Stack>
              <Box sx={{ 
                  height: 400,
                  width: '90%',
                  marginTop: 5
                  }}>
                <DataGrid
                  rows={rows}
                  columns={columns}
                  pageSize={10}
                  rowsPerPageOptions={[5]}  
                  onRowClick={e => selectedRow(e.row)}
                  
                />
              </Box>
            </Box>
          </div>
        </>
      )
    } else {
      return <LogOut />
    }
  }