apiVersion: batch/v1
kind: CronJob
metadata:
  name: extractor
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: extractor
            image: extractor:latest
            imagePullPolicy: Never
            env:
            - name: BACKEND_URL
              value: "http://backend:8000/count"
          restartPolicy: OnFailure
