"""init

Revision ID: 961862047ddc
Revises: 
Create Date: 2026-03-07 15:52:59.405993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961862047ddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeseries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeseries_label'), 'timeseries', ['label'], unique=True)
    op.create_table('timeseries_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeseries_id', 'timestamp', name='uq_timeseries_timestamp')
    )
    op.create_index('idx_timeseries_timestamp', 'timeseries_points', ['timeseries_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_timeseries_points_timeseries_id'), 'timeseries_points', ['timeseries_id'], unique=False)
    op.create_index(op.f('ix_timeseries_points_timestamp'), 'timeseries_points', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_points_timestamp'), table_name='timeseries_points')
    op.drop_index(op.f('ix_timeseries_points_timeseries_id'), table_name='timeseries_points')
    op.drop_index('idx_timeseries_timestamp', table_name='timeseries_points')
    op.drop_table('timeseries_points')
    op.drop_index(op.f('ix_timeseries_label'), table_name='timeseries')
    op.drop_table('timeseries')
    # ### end Alembic commands ###
