platform :ios, '17.6'

target 'dynamoxQuizChallenge' do
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  target 'dynamoxQuizChallengeTests' do
    inherit! :search_paths
  end

  target 'dynamoxQuizChallengeUITests' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.6'
    end
  end
end