
export const STORE_MACHINE_DATA = 'STORE_MACHINE_DATA';
export const UPDATE_MACHINE_DATA = 'UPDATE_MACHINE_DATA';
export const DELETE_MACHINE_DATA = 'DELETE_MACHINE_DATA';
export const STORE_SENSOR_DATA = 'STORE_SENSOR_DATA';
export const UPDATE_SENSOR_DATA = 'UPDATE_SENSOR_DATA';
export const DELETE_SENSOR_DATA = 'DELETE_SENSOR_DATA';