import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./api/auth/provider";
import { Providers } from "@/lib/providers";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
