import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="bg-blue flex items-center justify-between px-11 h-[120px]">
          <img src="/logo-dynamox.png" alt="dynamox logo" className="w-44" />
          <ul className="flex text-white gap-9 font-medium -mb-10">
            <li>DynaPredict</li>
            <li>Sensores</li>
            <li>Contato</li>
          </ul>
        </nav>
      </header>
      <section id="inicio" className="relative h-[calc(100vh-120px)]">
        <img
          src="/grafismo.png"
          alt="grafismo backgroud"
          className="absolute w-screen h-full object-cover"
        />
        <div>
          <h1>Solução DynaPredict</h1>
          <img src="/desktop-and-mobile.png" alt="" />
        </div>
      </section>
    </>
  );
}
