import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Image src="logo-dynamox.png" alt="dynamox logo" />
        <ul>
          <li>DynaPredict</li>
          <li>Sensores</li>
          <li>Contato</li>
        </ul>
      </nav>
    </>
  );
}
