import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="bg-blue flex items-center justify-between px-11 h-[120px]">
          <img src="/logo-dynamox.png" alt="dynamox logo" className="w-44" />
          <ul className="flex text-white gap-9 font-medium -mb-10">
            <li>DynaPredict</li>
            <li>Sensores</li>
            <li>Contato</li>
          </ul>
        </nav>
      </header>
      <section id="inicio" className="relative h-[calc(100vh-120px)]">
        <img
          src="/grafismo.png"
          alt="grafismo backgroud"
          className="absolute w-screen h-full object-cover"
        />
        <div className="flex justify-around items-center w-screen z-10 px-20">
          <div className="z-10 leading-snug gap-8">
            <h1 className="font-bold text-[80px] text-white">
              Solução DynaPredict
            </h1>
            <img src="/logo-dynapredict.png" alt="logo dynamox" />
          </div>
          <img
            src="/desktop-and-mobile.png"
            alt="desktop-and-mobile"
            className="z-10 w-[700px]"
          />
        </div>
      </section>
      <section
        id="sensores"
        className="flex flex-col justify-center items-center h-screen max-w-5xl mx-auto gap-4"
      >
        <h2 className="font-bold text-4xl text-black text-center">
          Sensores para Manutenção Preditiva
        </h2>
        <p className="text-center text-gray text-xl">
          Opções de sensores sem fio, ou DynaLoggers com sensores de vibração
          triaxial e temperatura embarcados, que comunicam por Bluetooth com o
          App mobile ou Gateway, registrando os dados monitorados em sua memória
          interna. Por conexão internet esses dados são centralizados na
          Plataforma DynaPredict Web para análise, prognóstico e tomada de
          decisão.
        </p>
        <Link
          href="#"
          className="text-white bg-blue px-11 py-2 rounded font-bold my-8"
        >
          VER MAIS
        </Link>
        <div className="grid grid-cols-3 text-center font-bold text-4xl text-lightBlue">
          <div>
            <img
              src="/sensor-tca.png"
              alt="sensor-tca"
              id="tca"
              className="w-[300px] object-cover"
            />
            <label htmlFor="tca">TcA+</label>
          </div>
          <div>
            <img
              src="/sensor-af.png"
              alt="sensor-af"
              id="af"
              className="w-[300px] object-cover"
            />
            <label htmlFor="af">AS</label>
          </div>
          <div>
            <img
              src="/sensor-hf.png"
              alt="sensor-hf"
              id="hf"
              className="w-[300px] object-cover"
            />
            <label htmlFor="hf">HF</label>
          </div>
        </div>
      </section>
    </>
  );
}
