export const machinesData = [
  {
    id: 1,
    machineId: "1234567890",
    name: "Machine A",
    type: "Fan",
    sensors: ["TcAg", "TcAs"],
    monitoringPoints: ["Point 1", "Point 2"],
  },
  {
    id: 2,
    machineId: "0987654321",
    name: "Machine B",
    type: "Fan",
    sensors: ["TcAs", "TcAg"],
    monitoringPoints: ["Point 3", "Point 4"],
  },
  {
    id: 3,
    machineId: "1122334455",
    name: "Machine C",
    type: "Pump",
    sensors: ["HF+"],
    monitoringPoints: ["Point 5"],
  },
  {
    id: 4,
    machineId: "2233445566",
    name: "Machine D",
    type: "Fan",
    sensors: ["TcAg"],
    monitoringPoints: ["Point 6"],
  },
  {
    id: 5,
    machineId: "3344556677",
    name: "Machine E",
    type: "Pump",
    sensors: ["HF+"],
    monitoringPoints: ["Point 7", "Point 8"],
  },
];
