"""rebuild schema with enums

Revision ID: da3fd1a1adfe
Revises: 6bcdf24d08ee
Create Date: 2026-02-27 10:44:06.917757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3fd1a1adfe'
down_revision: Union[str, Sequence[str], None] = '6bcdf24d08ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('metrics', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('metrics', 'metric_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RMS', 'PEAK', 'AVERAGE', 'STD', 'KURTOSIS', 'CREST_FACTOR', name='metric_type_enum'),
               existing_nullable=False)
    op.alter_column('metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('idx_metrics_signal_timestamp', 'metrics', ['signal_id', 'timestamp'], unique=False)
    op.create_index('idx_metrics_signal_type', 'metrics', ['signal_id', 'metric_type'], unique=False)
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_metrics_metric_type'), 'metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_metrics_signal_id'), 'metrics', ['signal_id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.add_column('signals', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('signals', 'signal_type',
               existing_type=postgresql.ENUM('VIBRATION', 'TEMPERATURE', 'PRESSURE', name='signaltype'),
               type_=sa.Enum('VIBRATION', 'TEMPERATURE', 'PRESSURE', name='signal_type_enum'),
               existing_nullable=False)
    op.alter_column('signals', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index('idx_machine_timestamp', 'signals', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_machine_id'), 'signals', ['machine_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_machine_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index('idx_machine_timestamp', table_name='signals')
    op.alter_column('signals', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('signals', 'signal_type',
               existing_type=sa.Enum('VIBRATION', 'TEMPERATURE', 'PRESSURE', name='signal_type_enum'),
               type_=postgresql.ENUM('VIBRATION', 'TEMPERATURE', 'PRESSURE', name='signaltype'),
               existing_nullable=False)
    op.drop_column('signals', 'created_at')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_signal_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_index('idx_metrics_signal_type', table_name='metrics')
    op.drop_index('idx_metrics_signal_timestamp', table_name='metrics')
    op.alter_column('metrics', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('metrics', 'metric_type',
               existing_type=sa.Enum('RMS', 'PEAK', 'AVERAGE', 'STD', 'KURTOSIS', 'CREST_FACTOR', name='metric_type_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('metrics', 'timestamp')
    op.alter_column('machines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
