[project]
name = "signal-processor-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "pydantic>=2.13.4",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "sqlalchemy>=2.0.49",
    "sqlmodel>=0.0.38",
    "psycopg2-binary",
    "pandas>=3.0.3",
]

[tool.pytest.ini_options]
pythonpath = [
  "app"
]
