name: Challenge 2 CI

on:
  push:
    paths:
      - 'challenge-2/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'challenge-2/**'
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./challenge-2

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './challenge-2/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fix lint error
        run: npm run format

      - name: Lint
        run: npm run lint
