name: KMP CI

on:
  push:
    branches: [ "main", "master", "container" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Common Tests
        run: ./gradlew :composeApp:testDebugUnitTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() 
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/*.xml'

      - name: Build Debug APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quiz-app-debug
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk