services:
  next-app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamox-next
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
